### PR TITLE
Add support for description field in heads

### PR DESCRIPTION
**Pull request by MikaelX**
Description field text will show up on the admin page for easier documentation and a good help for users

### CODE REVIEW

**Comment by MikaelX** [comment]
Please let me know if i've missed something when it comes to where to document that the description tag is a viable option on the heads, and/or I need to add it in more places.

**Comment by emanchado** [comment]
Hi Mikael, thanks for the patch!

Adding a new, optional field to all heads is easy, you just have to add the value 'description' to the IMPLICIT_OPTIONAL_PROPS array at the top of lib/heads.js.

I added it locally to check your change, and I'm not sure myself about the current solution, it's pretty non-obvious that clicking on a row will show a description. Another thing that bothers me is that because of how the CSS is made, the description row will take one of the alternating row colours, so that when the description is collapsed, there will be two rows with the same background colour. Finally, clicking on the attached/detached button produces a quirky behaviour, because the page is reloaded...

Have you seen it working, what do you think? Maybe it would be better to show the description somehow separately, like in a tool tip?

**Comment by MikaelX** [comment]
Hi

Thanks for getting back to me :) 

I'm back at the office on Monday and I have loads of things during the weekend. I can absolutely look into it. Adding support for jquery in the admin will help a lot too.

Here's what I wanted to achieve:

1. Easy documentation for people to understand the endpoint and its function
2. Add a test part below for inline testing

I'll get back more next week. 

Have a good weekend. 

// Mikael X Johansson
Hennes & Mauritz 

Skickat från min iPhone

**Comment by emanchado** [comment]
I thought about jQuery when I started writing the admin UI, but decided against it because I didn't have a lot of use for it and wanted to keep the page as simple as possible. Depending on what we end up doing here, it might be worth adding it.

I'm unsure about the inline testing, though. How useful is it, do you have use cases of the top of your head? Are you thinking about the people writing the plugins, or the people using them? I can't imagine that a lot of people using the plugins would need the inline tester. In comparison, I think I'd rather integrate some way to read the logs created by the "logger" plugin, from the admin UI. That helps understand what's going on when there are problems, which seems more useful for the plugin users.

Anyway, looking forward to your ideas!

**Comment by MikaelX** [comment]
Hi

So Monday is here, just wanted to explain how we use your tool here, also Gustav Weslien you have been talking to (about the proxy) is my Colleague and we’re working on this together.

We use the tool as a mock-service for our internal APIs which means that a lot of users are using the mock for testing which gives why I need the documentation and testing tool, we use headers for authentication due to the fact that our aged internal APIs use that and not oAuth2.

My plan if you approve is to add jQuery to the admin interface, fix the documentation in a good way and maybe add support for markdown documents to be placed and then rendered in place of some sort of documentation for a fully fletched system inside robohydra.

My current solution (forget the look on it right now) reads markdown files on our end and parses the html into the description field i’ve added, this is working pretty ok but as said the look will be improved, just kicked it together to show you my thoughts before i finished it.

Sincerely

MIKAEL X JOHANSSON
H & M HENNES & MAURITZ IT - CMS Team
ÅRSTAÄNGSVÄGEN 13, 117 43 STOCKHOLM, SWEDEN
PHONE: +46 8 5780 6257  MOBILE: +46 735 405301
EMAIL: mailto:mikaelx.johansson@hm.com

FOLLOW US ON:
www.hm.com<http://www.hm.com/>
www.facebook.com/hm<http://www.facebook.com/hm>
www.twitter.com/hm<http://www.twitter.com/hm>
www.youtube.com/hm<http://www.youtube.com/hm>


The information contained in this e-mail message may be privileged, confidential, and protected from disclosure. Any unauthorized use, printing, copying, disclosure or dissemination of this communication may be subject to legal restriction or sanction. If you think that you have received this e-mail message in error, please reply to the sender and delete this message from your computer.

**Comment by emanchado** [comment]
I'll drop you an e-mail, I need a bit more information to wrap my head around the exact usage, and you may not want to publish that information here and/or this thread will be cleaner without that discussion...

**Comment by MikaelX** [comment]
Sounds good, please do :) removed some messages

**Comment by emanchado** [comment]
Ah, no need to remove, I just didn't want to add a lot more messages while I understood exactly what you need. I'm a bit slow sometimes, you know? :-)

Anyway, message sent, check your spam folder just in case (in happens sometimes)...

**Comment by emanchado** [comment]
Did you get my e-mail?

**Comment by emanchado** [comment]
OK, closing for now, as there hasn't been any activity for over a year.

**Pull request closed without merging**
